"""end_at

Revision ID: 0002
Revises: 0001
Create Date: 2024-03-25 20:48:41.321208

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("locations", sa.Column("end_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "locations", "start_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "locations", "start_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("locations", "end_at")
    # ### end Alembic commands ###
