"""name to title

Revision ID: 0006
Revises: 0005
Create Date: 2024-03-21 18:41:19.614981

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cities", "name", new_column_name="title")
    op.alter_column("countries", "name", new_column_name="title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cities", "title", new_column_name="name")
    op.alter_column("countries", "title", new_column_name="name")
    # ### end Alembic commands ###
