"""'tg_username'

Revision ID: 0007
Revises: 0006
Create Date: 2024-03-23 23:13:49.072216

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: Union[str, None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_countries_alpha2"), "countries", ["alpha2"])
    op.create_unique_constraint(op.f("uq_countries_title"), "countries", ["title"])
    op.add_column(
        "users", sa.Column("tg_username", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tg_username")
    op.drop_constraint(op.f("uq_countries_title"), "countries", type_="unique")
    op.drop_constraint(op.f("uq_countries_alpha2"), "countries", type_="unique")
    # ### end Alembic commands ###
